### ISSUE TITLE
How to pass ERROR of ContestWebServer 

### ISSUE THREAD

**Issue by vuhatuananh** [cms-dev/cms#1071]
How to pass ERROR of ContestWebServer (CMS 1.5.dev0 on Ubuntu 18.10)

2018-11-08 23:43:13,782 - INFO [Contest,0] ContestWebServer 0 up and running!
2018-11-08 23:43:20,661 - INFO [Contest,0] Unsuccessful cookie authentication: no cookie provided
2018-11-08 23:43:20,662 - ERROR [Contest,0] Uncaught exception GET / (::ffff:192.168.11.205)
HTTPServerRequest(protocol='http', host='192.168.11.239:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::ffff:192.168.11.205', headers={'Host': '192.168.11.239:8888', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|c25aa454|46837b25984a05f09d7cd915cc68d566|1541748421; awslogin="egupOjqnf4eg/r+X7M0YiutUdCQ=?id=MQ==&ip=Ijo6ZmZmZjoxOTIuMTY4LjExLjIwNSI=&timestamp=MTU0MTc0OTM4NS44MjY1OTQ2"', 'Upgrade-Insecure-Requests': '1', 'Cache-Control': 'max-age=0'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 86, in prepare
    self.r_params = self.render_params()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 176, in render_params
    if self.current_user is not None:
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1158, in current_user
    self._current_user = self.get_current_user()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
    self.clear_cookie(cookie_name)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 580, in clear_cookie
    domain=domain)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 543, in set_cookie
    raise ValueError("Invalid cookie %r: %r" % (name, value))
ValueError: Invalid cookie 'OLP 2018_login': ''
2018-11-08 23:43:20,664 - ERROR [Contest,0] Uncaught exception (ValueError("Invalid cookie 'OLP 2018_login': ''",)) while processing a request: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 86, in prepare
    self.r_params = self.render_params()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 176, in render_params
    if self.current_user is not None:
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1158, in current_user
    self._current_user = self.get_current_user()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
    self.clear_cookie(cookie_name)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 580, in clear_cookie
    domain=domain)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 543, in set_cookie
    raise ValueError("Invalid cookie %r: %r" % (name, value))
ValueError: Invalid cookie 'OLP 2018_login': ''

2018-11-08 23:43:20,665 - ERROR [Contest,0] 500 GET / (::ffff:192.168.11.205) 9.97ms
::ffff:192.168.11.205 - - [2018-11-08 23:43:20] "GET / HTTP/1.1" 500 197 0.039582
2018-11-08 23:43:20,925 - WARNING [Contest,0] 404 GET /favicon.ico (::ffff:192.168.11.205) 0.98ms
::ffff:192.168.11.205 - - [2018-11-08 23:43:20] "GET /favicon.ico HTTP/1.1" 404 221 0.002944

Thank you!

**Comment by stefano-maggiolo** [comment]
Please use a contest name without spaces.

@lerks didn't we limit the character set?

**Comment by vuhatuananh** [comment]
That's OK! Thank you!

**Comment by lerks** [comment]
It was in fact a bug: #1073 contains a fix.
