### ISSUE TITLE
Contest name with special characters causes HTTP 500 in CWS

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#1099]
There are two variants of the issue. How to reproduce:

1. Run CWS in multi-contest mode
2. Clear cookies
3. Navigate to given path

### Variant 1

Relative path: `/test"`
<details><summary>Result</summary>

```
jan 19 11:07:11 bionic cmsLogService[21243]: 2019-01-19 11:07:11,143 - INFO [Contest,0] Unsuccessful cookie authentication: no cookie provided
jan 19 11:07:11 bionic cmsLogService[21243]: 2019-01-19 11:07:11,145 - ERROR [Contest,0] Uncaught exception GET /test%22 (10.0.2.2)
jan 19 11:07:11 bionic cmsLogService[21243]: HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/test%22', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Host': 'localhost:8080', 'X-Real-Ip': '10.0.2.2', 'X-Forwarded-For': '10.0.2.2', 'X-Forwarded-Proto': 'http', 'Connection': 'close', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'ru,en;q=0.7,lv;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Dnt': '1', 'Upgrade-Insecure-Requests': '1'})
jan 19 11:07:11 bionic cmsLogService[21243]: Traceback (most recent call last):
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1489, in _execute
jan 19 11:07:11 bionic cmsLogService[21243]:     result = self.prepare()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 67, in prepare
jan 19 11:07:11 bionic cmsLogService[21243]:     self.choose_contest()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 109, in choose_contest
jan 19 11:07:11 bionic cmsLogService[21243]:     self.r_params = super().render_params()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/base.py", line 134, in render_params
jan 19 11:07:11 bionic cmsLogService[21243]:     ret["xsrf_form_html"] = self.xsrf_form_html()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1350, in xsrf_form_html
jan 19 11:07:11 bionic cmsLogService[21243]:     escape.xhtml_escape(self.xsrf_token) + '"/>'
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1233, in xsrf_token
jan 19 11:07:11 bionic cmsLogService[21243]:     expires_days = 30 if self.current_user else None
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1158, in current_user
jan 19 11:07:11 bionic cmsLogService[21243]:     self._current_user = self.get_current_user()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
jan 19 11:07:11 bionic cmsLogService[21243]:     self.clear_cookie(cookie_name)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 580, in clear_cookie
jan 19 11:07:11 bionic cmsLogService[21243]:     domain=domain)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 548, in set_cookie
jan 19 11:07:11 bionic cmsLogService[21243]:     self._new_cookie[name] = value
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 523, in __setitem__
jan 19 11:07:11 bionic cmsLogService[21243]:     self.__set(key, rval, cval)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 513, in __set
jan 19 11:07:11 bionic cmsLogService[21243]:     M.set(key, real_value, coded_value)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 380, in set
jan 19 11:07:11 bionic cmsLogService[21243]:     raise CookieError('Illegal key %r' % (key,))
jan 19 11:07:11 bionic cmsLogService[21243]: http.cookies.CookieError: Illegal key 'test"_login'
jan 19 11:07:11 bionic cmsLogService[21243]: 2019-01-19 11:07:11,149 - ERROR [Contest,0] Uncaught exception (CookieError('Illegal key \'test"_login\'',)) while processing a request: Traceback (most recent call last):
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1489, in _execute
jan 19 11:07:11 bionic cmsLogService[21243]:     result = self.prepare()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 67, in prepare
jan 19 11:07:11 bionic cmsLogService[21243]:     self.choose_contest()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 109, in choose_contest
jan 19 11:07:11 bionic cmsLogService[21243]:     self.r_params = super().render_params()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/base.py", line 134, in render_params
jan 19 11:07:11 bionic cmsLogService[21243]:     ret["xsrf_form_html"] = self.xsrf_form_html()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1350, in xsrf_form_html
jan 19 11:07:11 bionic cmsLogService[21243]:     escape.xhtml_escape(self.xsrf_token) + '"/>'
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1233, in xsrf_token
jan 19 11:07:11 bionic cmsLogService[21243]:     expires_days = 30 if self.current_user else None
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1158, in current_user
jan 19 11:07:11 bionic cmsLogService[21243]:     self._current_user = self.get_current_user()
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
jan 19 11:07:11 bionic cmsLogService[21243]:     self.clear_cookie(cookie_name)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 580, in clear_cookie
jan 19 11:07:11 bionic cmsLogService[21243]:     domain=domain)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 548, in set_cookie
jan 19 11:07:11 bionic cmsLogService[21243]:     self._new_cookie[name] = value
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 523, in __setitem__
jan 19 11:07:11 bionic cmsLogService[21243]:     self.__set(key, rval, cval)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 513, in __set
jan 19 11:07:11 bionic cmsLogService[21243]:     M.set(key, real_value, coded_value)
jan 19 11:07:11 bionic cmsLogService[21243]:   File "/usr/lib/python3.6/http/cookies.py", line 380, in set
jan 19 11:07:11 bionic cmsLogService[21243]:     raise CookieError('Illegal key %r' % (key,))
jan 19 11:07:11 bionic cmsLogService[21243]: http.cookies.CookieError: Illegal key 'test"_login'
jan 19 11:07:11 bionic cmsLogService[21243]: 2019-01-19 11:07:11,155 - ERROR [Contest,0] 500 GET /test%22 (10.0.2.2) 17.83ms
```
</details>

### Variant 2

Relative path: `/test test`
<details><summary>Result</summary>

```
jan 19 11:14:35 bionic cmsLogService[21243]: 2019-01-19 11:14:35,658 - INFO [Contest,0] Unsuccessful cookie authentication: no cookie provided
jan 19 11:14:35 bionic cmsLogService[21243]: 2019-01-19 11:14:35,661 - ERROR [Contest,0] Uncaught exception GET /test%20test (10.0.2.2)
jan 19 11:14:35 bionic cmsLogService[21243]: HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/test%20test', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Host': 'localhost:8080', 'X-Real-Ip': '10.0.2.2', 'X-Forwarded-For': '10.0.2.2', 'X-Forwarded-Proto': 'http', 'Connection': 'close', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'ru,en;q=0.7,lv;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Dnt': '1', 'Upgrade-Insecure-Requests': '1'})
jan 19 11:14:35 bionic cmsLogService[21243]: Traceback (most recent call last):
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1489, in _execute
jan 19 11:14:35 bionic cmsLogService[21243]:     result = self.prepare()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 67, in prepare
jan 19 11:14:35 bionic cmsLogService[21243]:     self.choose_contest()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 109, in choose_contest
jan 19 11:14:35 bionic cmsLogService[21243]:     self.r_params = super().render_params()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/base.py", line 134, in render_params
jan 19 11:14:35 bionic cmsLogService[21243]:     ret["xsrf_form_html"] = self.xsrf_form_html()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1350, in xsrf_form_html
jan 19 11:14:35 bionic cmsLogService[21243]:     escape.xhtml_escape(self.xsrf_token) + '"/>'
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1233, in xsrf_token
jan 19 11:14:35 bionic cmsLogService[21243]:     expires_days = 30 if self.current_user else None
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1158, in current_user
jan 19 11:14:35 bionic cmsLogService[21243]:     self._current_user = self.get_current_user()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
jan 19 11:14:35 bionic cmsLogService[21243]:     self.clear_cookie(cookie_name)
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 580, in clear_cookie
jan 19 11:14:35 bionic cmsLogService[21243]:     domain=domain)
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 543, in set_cookie
jan 19 11:14:35 bionic cmsLogService[21243]:     raise ValueError("Invalid cookie %r: %r" % (name, value))
jan 19 11:14:35 bionic cmsLogService[21243]: ValueError: Invalid cookie 'test test_login': ''
jan 19 11:14:35 bionic cmsLogService[21243]: 2019-01-19 11:14:35,663 - ERROR [Contest,0] Uncaught exception (ValueError("Invalid cookie 'test test_login': ''",)) while processing a request: Traceback (most recent call last):
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1489, in _execute
jan 19 11:14:35 bionic cmsLogService[21243]:     result = self.prepare()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 67, in prepare
jan 19 11:14:35 bionic cmsLogService[21243]:     self.choose_contest()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 109, in choose_contest
jan 19 11:14:35 bionic cmsLogService[21243]:     self.r_params = super().render_params()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/base.py", line 134, in render_params
jan 19 11:14:35 bionic cmsLogService[21243]:     ret["xsrf_form_html"] = self.xsrf_form_html()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1350, in xsrf_form_html
jan 19 11:14:35 bionic cmsLogService[21243]:     escape.xhtml_escape(self.xsrf_token) + '"/>'
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1233, in xsrf_token
jan 19 11:14:35 bionic cmsLogService[21243]:     expires_days = 30 if self.current_user else None
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1158, in current_user
jan 19 11:14:35 bionic cmsLogService[21243]:     self._current_user = self.get_current_user()
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/server/contest/handlers/contest.py", line 156, in get_current_user
jan 19 11:14:35 bionic cmsLogService[21243]:     self.clear_cookie(cookie_name)
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 580, in clear_cookie
jan 19 11:14:35 bionic cmsLogService[21243]:     domain=domain)
jan 19 11:14:35 bionic cmsLogService[21243]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 543, in set_cookie
jan 19 11:14:35 bionic cmsLogService[21243]:     raise ValueError("Invalid cookie %r: %r" % (name, value))
jan 19 11:14:35 bionic cmsLogService[21243]: ValueError: Invalid cookie 'test test_login': ''
jan 19 11:14:35 bionic cmsLogService[21243]: 2019-01-19 11:14:35,671 - ERROR [Contest,0] 500 GET /test%20test (10.0.2.2) 15.43ms
```
</details>

We observed this on our public-facing server when it was scanned by some bot.

**Comment by eliasffyksen** [comment]
Hi, found the solution while trying to implement oauth login. The cookie name can not have space, and the cookie name includes the contest name. I'll make a pull request for it now. Can someone plz approve it :)

**Comment by andreyv** [comment]
Hi @eliasffyksen :)

I think it is better to not even try to set cookies for invalid contest names. Contest names have the `Codename` constraint, so a space or a quotation mark is not possible: https://github.com/cms-dev/cms/blob/d4c9e926bd52d8022069c417b206b0882ef4d1ba/cms/db/contest.py#L62-L63

Perhaps the request handler can query the database earlier and immediately return HTTP 404 if contest is not found. Or cookies can be set later.

**Comment by eliasffyksen** [comment]
@andreyv I was perfectly able to make a contest name with spaces in, so there might be something wrong with that constraint. I'll look in to it. I would anyways like to add some better error logging for invalid cookies, because it was a nightmare to debug, if you guys are open to that?

**Comment by andreyv** [comment]
@eliasffyksen Do you use version 1.4 or master? Looks like 9da2d146d8306464e49dc2bccc982f3fca9bfb8c wasn't backported to 1.4.

**Comment by andreyv** [comment]
So I just re-checked, and the two variants in this issue are actually a duplicate of #1071. Probably I didn't have 9da2d146d8306464e49dc2bccc982f3fca9bfb8c either when opening the issue.

Both variants now properly return error 404 on master.

@eliasffyksen You could try applying 9da2d146d8306464e49dc2bccc982f3fca9bfb8c or upgrading to master to prevent such errors.

**Comment by eliasffyksen** [comment]
@andreyv Thanks, I'll try that

**Comment by andreyv** [comment]
Closing as a duplicate of #1071.
