### ISSUE TITLE
Invalid memory_limit bigint modulo constraint

### ISSUE THREAD

**Issue by cantonios** [cms-dev/cms#1112]
## Issue with bigint modulo operator

**Description:**

The recently added line
https://github.com/cms-dev/cms/blob/bfb359ba21935785b47ecb21b86ff4fcdb1f3522/cms/db/task.py#L393

 broke for `cmsInitDB` for me, since I have no `bigint %% int` (nor `bigint %% bigint`) operator

```
2019-02-12 13:38:49,716 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: operator does not exist: bigint %% integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cmsInitDB", line 4, in <module>
    __import__('pkg_resources').run_script('cms==1.5.dev0', 'cmsInitDB')
  File "/home/antonio/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/antonio/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/EGG-INFO/scripts/cmsInitDB", line 59, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/EGG-INFO/scripts/cmsInitDB", line 53, in main
    success = init_db()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.5.dev0-py3.6.egg/cms/db/init.py", line 29, in init_db
    metadata.create_all()
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: bigint %% integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: '\nCREATE TABLE datasets (\n\tid SERIAL NOT NULL, \n\ttask_id INTEGER NOT NULL, \n\tdescription VARCHAR NOT NULL, \n\tautojudge BOOLEAN NOT NULL, \n\ttime_limit FLOAT CHECK (time_limit > 0), \n\tmemory_limit BIGINT CHECK (memory_limit %%%% 1048576 = 0) CHECK (memory_limit > 0), \n\ttask_type VARCHAR NOT NULL, \n\ttask_type_parameters JSONB NOT NULL, \n\tscore_type VARCHAR NOT NULL, \n\tscore_type_parameters JSONB NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (task_id, description), \n\tUNIQUE (id, task_id), \n\tFOREIGN KEY(task_id) REFERENCES tasks (id) ON DELETE CASCADE ON UPDATE CASCADE\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)
```

### System Information

**CMS version:** master
**Was CMS installed:** yes
**Using a virtualenv:** no
**Postgres version:** 10.6
**Distribution and version:** Ubuntu 18.10

**Comment by stefano-maggiolo** [comment]
What version of sqlalchemy are you using?

**Comment by stefano-maggiolo** [comment]
To expand: we support sqlalchemy 1.1, if you are on a more recent version it might be that now that double percent must be a single one. I couldn't really understand from the changelog, but they did some work around percent and escaping (seems unrelated to this case, but I'm not sure), so it's a possibility.

Suggestion: the easiest way to run with all the correct dependency versions is to use virtualenv.

**Comment by cantonios** [comment]
I see, I do have sqlalchemy 1.2.8, which is installed by default on Ubuntu 18.10.

**Comment by stefano-maggiolo** [comment]
The sandbox only allows KiB multiples, so we need at most that granularity. I think that MiB was chosen because it simplify some UI treatment and anyway it's more or less meaningless to enforce memory limits with granularity higher than 1 MiB.

Thanks for finding this, it will be useful when we migrate to the next version of alchemy!
