### ISSUE TITLE
socket.error: [Errno 98] Address already in use:  (u'', 9888)

### ISSUE THREAD

**Issue by nilehmann** [cms-dev/cms#415]
When I try to start the ContestWebServer (running cmsContestWebServer) I get the followig error. I already checked and no application is listening on the port. Moreover it happens with any port I choose. Curisouly the server start and I'm able to enter the contest in the browser but the script stop with this error.

    Traceback (most recent call last):
    File "/usr/bin/cmsContestWebServer", line 52, in <module>
      sys.exit(0 if main() is True else 1)
    File "/usr/bin/cmsContestWebServer", line 47, in main
      ask_contest=ask_for_contest).run()
    File "/usr/lib/python2.7/site-packages/cms/io/web_service.py", line 79, in run
      self.web_server.start()
    File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 234, in start
      self.init_socket()
    File "/usr/lib/python2.7/site-packages/gevent/pywsgi.py", line 639, in init_socket
      StreamServer.init_socket(self)
    File "/usr/lib/python2.7/site-packages/gevent/server.py", line 78, in init_socket
      self.socket = self.get_listener(self.address, self.backlog, self.family)
    File "/usr/lib/python2.7/site-packages/gevent/server.py", line 89, in get_listener
      return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
    File "/usr/lib/python2.7/site-packages/gevent/server.py", line 153, in _tcp_listener
      sock.bind(address)
    File "<string>", line 1, in bind
    socket.error: [Errno 98] Address already in use: (u'', 8888)

**Comment by wil93** [comment]
Maybe you started `cmsResourceService` (which activates instances of other CMS services, CWS being one of them), and then you tried to start `cmsContestWebServer` (which was already started by RS).

**Comment by nilehmann** [comment]
Yes, that was the problem. Sorry for the inconvinience. I'm trying CMS for the first time.

**Comment by wil93** [comment]
No worries :smile:
