### ISSUE TITLE
Issue occurring when executing cmsAdminWebServer

### ISSUE THREAD

**Issue by ConanKun** [cms-dev/cms#425]
Hi, I installed cms just before, but I encountered a severe problem.

when I executed cmsAdminWebServer, it said

Traceback (most recent call last):
  File "/usr/local/bin/cmsAdminWebServer", line 5, in <module>
    pkg_resources.run_script('cms==1.2.0', 'cmsAdminWebServer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsAdminWebServer", line 34, in <module>
    from cms.server.AdminWebServer import AdminWebServer
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/AdminWebServer.py", line 56, in <module>
    from cms.grading import compute_changes_for_dataset
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/__init__.py", line 43, in <module>
    from cms.grading.Sandbox import Sandbox
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/Sandbox.py", line 38, in <module>
    from gevent import subprocess
ImportError: cannot import name subprocess

what should I do to make it work okay?

thanks

**Comment by wil93** [comment]
It looks like you are missing `gevent`. Are you on Ubuntu? In that case try to issue:

    sudo apt-get install python-gevent

Make sure to follow [the documentation](http://cms.readthedocs.org/en/v1.2/Installation.html#dependencies).

**Comment by ConanKun** [comment]
@wil93 I executed apt-get install python-gevent, but it's already installed.

is there another reason for the error?(I can't find any troubleshooting in the instruction. I just followed it exactly)

**Comment by stefano-maggiolo** [comment]
Which version it is? Can you paste the output of

dpkg -l python-gevent

**Comment by ConanKun** [comment]
@stefano-maggiolo it says  ii  python-gevent                    0.13.6-1ubuntu1                  gevent is a coroutine-based Python networking library

**Comment by stefano-maggiolo** [comment]
Yes, we need  1.0.something (see https://cms.readthedocs.org/en/v1.2/Installation.html ).

If you are using an Ubuntu < 14.04 you can try install it with pip. Let us know if you need more guidance

**Comment by ConanKun** [comment]
Thanks the problem resolved!!
