### ISSUE TITLE
With SQLAlchemy>=1.0 smartmappedcollection.py fails

### ISSUE THREAD

**Issue by lerks** [cms-dev/cms#432]
When using the 1.0 version of SQLAlchemy one assumption of `smartmappedcollection.py` dosn't hold anymore. This can be triggered, by example, by launching `cmsAddTask`. The following trace is produced:
```
Traceback (most recent call last):
  File "/usr/bin/cmsAddTask", line 9, in <module>
    load_entry_point('cms==1.3.0rc0', 'console_scripts', 'cmsAddTask')()
  File "/usr/lib/python2.7/site-packages/cms-1.3.0rc0-py2.7.egg/cmscontrib/AddTask.py", line 114, in main
    loader_class=loader_class
  File "/usr/lib/python2.7/site-packages/cms-1.3.0rc0-py2.7.egg/cmscontrib/AddTask.py", line 69, in do_import
    task = self.loader.get_task()
  File "/usr/lib/python2.7/site-packages/cms-1.3.0rc0-py2.7.egg/cmscontrib/loaders/italy_yaml.py", line 468, in get_task
    task = Task(**args)
  File "<string>", line 4, in __init__
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/cms-1.3.0rc0-py2.7.egg/cms/db/base.py", line 224, in __init__
    setattr(self, prp.key, val)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1022, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1057, in _set_iterable
    collections.bulk_replace(new_values, old_collection, new_collection)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/collections.py", line 790, in bulk_replace
    new_adapter.append_with_event(member)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/collections.py", line 653, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/collections.py", line 1529, in set
    self.__setitem__(key, value, _sa_initiator)
  File "/usr/lib/python2.7/site-packages/cms-1.3.0rc0-py2.7.egg/cms/db/smartmappedcollection.py", line 186, in __setitem__
    assert self._linked
AssertionError
```

**Comment by lerks** [comment]
Fixed in 2f62cfed01207d592255cfdecafe8ed84e3b8b93.
