### ISSUE TITLE
IOError: Couldn't open large object.

### ISSUE THREAD

**Issue by ken8203** [cms-dev/cms#497]
Hi, I got a problem below:

```
2015/11/18 20:12:08 - ERROR [EvaluationService,0] Worker,1 signaled RPC for method precache_files was unsuccessful: IOError: Couldn't open large object.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/io/rpc.py", line 376, in process_incoming_request
    response["__data"] = method(**request["__data"])
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 94, in precache_files
    self.file_cacher.load(digest, if_needed=True)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/filecacher.py", line 451, in load
    fobj = self.backend.get_file(digest)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/filecacher.py", line 232, in get_file
    return fso.get_lobject(mode='rb')
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/fsobject.py", line 397, in get_lobject
    lobj = LargeObject(self.loid, mode)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/fsobject.py", line 120, in __init__
    "Couldn't open large object.", cursor)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/fsobject.py", line 169, in _execute
    raise IOError(message)
IOError: Couldn't open large object.
```

It's a strange problem, how can I solve it?
Something about permission??

Thanks a lot!

**Comment by giomasce** [comment]
Hi.

Please, do not use the bug tracker to receive support. Please write us on the users' mailing list (see https://cms-dev.github.io/).

However, about your problem, could you please write us which PostgreSQL version you are using and check whether there are errors in the logs in `/var/lib/postgresql/` (the location may change depending on your OS, which you should also tell us).

Regards, Giovanni.

**Comment by wil93** [comment]
@ken8203 You can also use the chat https://gitter.im/cms-dev/cms
