### ISSUE TITLE
Custom testing assigns random operations

### ISSUE THREAD

**Issue by JavkTheRipper** [cms-dev/cms#537]
Using the custom test interface generates an error : 

2016-02-11 17:07:34,082 - INFO [Contest,0] All files stored for test sent by demo
2016-02-11 17:07:34,140 - INFO [Contest,0] 302 POST /tasks/sum/test (127.0.0.1) 93.77ms
2016-02-11 17:07:34,173 - ERROR [Contest,0] EvaluationService,0 signaled RPC for method new_user_test was unsuccessful: TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request
    response["__data"] = method(**request["__data"])
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 855, in new_use$_test
    self.user_test_enqueue_operations(user_test)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 262, in user_te$t_enqueue_operations
    if self.enqueue(operation, priority, timestamp):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 153, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 476, in enqueue
    if self.operation_busy(operation):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 458, in operati$n_busy
    operation.dataset_id)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 441, in user_te$t_busy
    for operation in operations])
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 98, in __contai$s__
    return super(EvaluationExecutor, self).__contains__(item) or \
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/triggeredservice.py", line 76, in __contains__
    return item in self._operation_queue
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/priorityqueue.py", line 158, in __contains__
    return item in self._reverse
TypeError: unhashable type: 'list'
.

And will randomly add an operation that is either redundant or invalid to the queue:

2016-02-11 17:09:55,668 - INFO [Evaluation,0] `compile on 3 against dataset 1' completed. Success: True.
2016-02-11 17:09:55,673 - ERROR [Evaluation,0] RPC callback for Worker.execute_job raised exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 647, in run_callback
    func(data, plus, error=error)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 153, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/EvaluationService.py", line 557, in action_finished
    submission_result = submission.get_result(dataset)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/submission.py", line 122, in get_result
    assert self.task_id == dataset.task_id
AssertionError

**Comment by stefano-maggiolo** [comment]
https://github.com/cms-dev/cms/commit/746d5787bd2d37215791e27ae4df2ab9f9e7004c should have fixed this, please reopen if not. Thanks for reporting!
