### ISSUE TITLE
Cannot start services using different usernames

### ISSUE THREAD

**Issue by akmohtashami** [cms-dev/cms#579]
When trying to start CMS services as different usernames an exception is raised similar to below which was raised by ScoringService:
```
Traceback (most recent call last):
  File "/usr/local/bin/cmsScoringService", line 4, in <module>
    __import__('pkg_resources').run_script('cms==1.3.dev0', 'cmsScoringService')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1636, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsScoringService", line 51, in <module>
    sys.exit(0 if main() is True else 1)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsScoringService", line 46, in main
    ScoringService).run()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/util.py", line 230, in default_argument_parser
    return cls(args.shard)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/ScoringService.py", line 135, in __init__
    super(ScoringService, self).__init__(shard)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/triggeredservice.py", line 212, in __init__
    Service.__init__(self, shard)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/service.py", line 96, in __init__
    self.initialize_logging()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/service.py", line 134, in initialize_logging
    mode='w', encoding='utf-8')
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 930, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: u'/var/local/log/cms/ScoringService-0/2016-03-07-23-04-21.log'
```
I think the solution would be to set log and cache files' owner to cmsuser.

**Comment by stefano-maggiolo** [comment]
Hi Amir, in theory the files and directories there should be with 0660 and 0770 permissions respectively, can you tell me what is failing to be so?

**Comment by akmohtashami** [comment]
`/var/local/log/cms/ScoringService-0/` permission is set to 0760. It seems that even though `/var/local/log/cms/` permission is set to 0770 as you said, services' directories' permissions are not set correctly.

**Comment by akmohtashami** [comment]
The only service that seems to be handling permissions correctly is AdminWebServer.

**Comment by stefano-maggiolo** [comment]
Interesting :)
I'll check it out when I'll have some more time. Thanks!

**Comment by akmohtashami** [comment]
It seems that my previous comment was wrong. cmsAdminWebServer has the same problem as well. The problem is because these directories are created by `cms.util.mkdir` which doesn't handle setting permissions. Is it a good idea to set mode of directories created by this method to 0770 by default? Note that the above-mentioned problem happens in cache directory as well.

**Comment by stefano-maggiolo** [comment]
Thanks for the fix, this should be fixed
