### ISSUE TITLE
Error while adding a test case to a task

### ISSUE THREAD

**Issue by shivam312** [cms-dev/cms#666]
While adding the test case to the task i get an error. After submitting it shows error 500. And any page related to the task shows the same.
And the following is printed on the command line  : 

```
`2016/10/19 03:57:49 - ERROR [AdminWebServer,0] Uncaught exception GET /task/7 (172.16.193.1)
HTTPServerRequest(protocol='http', host='172.16.193.161:8889', method='GET', uri='/task/7', version='HTTP/1.1', remote_ip='172.16.193.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'If-None-Match': '"89a26cee227ab04e8c6bd7e32ccc408b97203e7f"', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': '172.16.193.161:8889', 'Referer': 'http://172.16.193.161:8889/add_testcase/7', 'Cache-Control': 'max-age=0', 'Cookie': 'login="2|1:0|10:1476730150|5:login|52:KFZBQQpwMApWQUEKcDEKRjE0NzY3MzAxNTAuODgwNDE0CnRwMgou|6085a23c95cba3a28993585825af5c9143d23616d61347cb703e8ce20274fab5"; unread_count="2|1:0|10:1476730286|12:unread_count|4:MA==|d5bb94c258684df0cbf4e153f8466a7d3d998f336514d7170a0a7cb27b1c4f2d"', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
 result = method(_self.path_args, *_self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/AdminWebServer.py", line 1506, in get
 self.render("task.html", **self.r_params)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 664, in render
 html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 771, in render_string
 return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/template.py", line 278, in generate
 return execute()
  File "task_html.generated.py", line 965, in _tt_execute
 for codename, testcase in sorted(dataset.testcases.iteritems()):  # task.html:266 (via base.html:129)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
 return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 599, in get
 return self.set_committed_value(state, dict_, value)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1077, in set_committed_value
 collection.append_multiple_without_event(value)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 664, in append_multiple_without_event
 appender(item, _sa_initiator=False)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1530, in set
 self.__setitem__(key, value, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/smartmappedcollection.py", line 186, in __setitem__
 assert self._linked
AssertionError
2016/10/19 03:57:49 - ERROR [AdminWebServer,0] Uncaught exception (AssertionError()) while processing a request: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
 result = method(_self.path_args, *_self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/AdminWebServer.py", line 1506, in get
 self.render("task.html", **self.r_params)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 664, in render
 html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 771, in render_string
 return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/template.py", line 278, in generate
 return execute()
  File "task_html.generated.py", line 965, in _tt_execute
 for codename, testcase in sorted(dataset.testcases.iteritems()):  # task.html:266 (via base.html:129)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
 return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 599, in get
 return self.set_committed_value(state, dict_, value)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1077, in set_committed_value
 collection.append_multiple_without_event(value)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 664, in append_multiple_without_event
 appender(item, _sa_initiator=False)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1530, in set
 self.__setitem__(key, value, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/smartmappedcollection.py", line 186, in __setitem__
 assert self._linked
AssertionError
2016/10/19 03:57:49 - ERROR [AdminWebServer,0] 500 GET /task/7 (172.16.193.1) 37.93ms
172.16.193.1 - - [2016-10-19 03:57:49] "GET /task/7 HTTP/1.1" 500 4453 0.038717
```

How can I solve the issue?

**Comment by stefano-maggiolo** [comment]
Hi, sorry for the very late reply. I cannot check, but I think this might happen because you have a too old (or too new) version of sqlalchemy. 0.9 or 1.0 should work.

**Comment by lerks** [comment]
This may be related to #736. Or anyway the solution discussed there would fix this as well.

PS: nice issue number ;)

**Comment by lerks** [comment]
SMC has been removed, this issue should not occur anymore.
