### ISSUE TITLE
Failed assertion when importing contest in the Italian (YAML) format

### ISSUE THREAD

**Issue by claudio-alvarez** [cms-dev/cms#674]
Hi all,
This is my first attempt to try CMS and I am having a hard time trying to import the example contest available at https://github.com/cms-dev/con_test

I installed CMS version 1.2.0 on Ubuntu Server 16.04, created and configured the PostgreSQL database as documented, and when I issue the cmsImport command, I get the following failed assertion:

[File: cms-output.txt](https://github.com/cms-dev/cms/files/604664/cms-output.txt)

`2016/11/21 16:49:42 - INFO [None] Creating database structure.
2016/11/21 16:49:42 - INFO [None] Loading parameters for contest con_test.
2016/11/21 16:49:42 - INFO [None] Contest parameters loaded.
2016/11/21 16:49:42 - INFO [None] Loading parameters for task batch.
Traceback (most recent call last):
  File "/usr/local/bin/cmsImporter", line 9, in <module>
    load_entry_point('cms==1.2.0', 'console_scripts', 'cmsImporter')()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscontrib/Importer.py", line 169, in main
    loader_class=loader_class).do_import()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscontrib/Importer.py", line 100, in do_import
    contest.tasks.append(self.loader.get_task(task))
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscontrib/YamlLoader.py", line 446, in get_task
    task = Task(**args)
  File "<string>", line 4, in __init__
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/base.py", line 224, in __init__
    setattr(self, prp.key, val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1027, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1062, in _set_iterable
    collections.bulk_replace(new_values, old_collection, new_collection)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 791, in bulk_replace
    new_adapter.append_with_event(member)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 654, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1530, in set
    self.__setitem__(key, value, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/db/smartmappedcollection.py", line 186, in __setitem__
    assert self._linked
AssertionError
`

The failed assertion occurs with the original example contest files with no modifications. I tried leaving just one task in the contest.yaml file and I am getting the same error. I tried to dive into the code to understand the failed assertion, but cannot figure out what the problem is. Any ideas?

**Comment by claudio-alvarez** [comment]
I just found out this issue is related to #432 
What would be the best solution in this case? Should I manually attempt to update smartmappedcollection.py as in 2f62cfe?

**Comment by claudio-alvarez** [comment]
I downgraded to SQLAlchemy 0.9.10 and could finally import the contest.

**Comment by stefano-maggiolo** [comment]
Sorry for the missing answers, but looks like you managed to solve everything!

**Comment by stefano-maggiolo** [comment]
That's awesome!
