### ISSUE TITLE
Worker fails when the cache is removed without restarting the process

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#677]
I want to periodically remove the cache because it is too heavy during my contest. However, the worker does not simply re-populate it (downloading testcases and so on) but it crashes instead.

```
2016-11-28 02:02:24,017 - ERROR [Worker,1 24 Worker::execute_job_group] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 122, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 190, in compile
    sandbox.create_file_from_storage(filename, digest)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/grading/Sandbox.py", line 309, in create_file_from_storage
    self.file_cacher.get_file_to_fobj(digest, file_)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/filecacher.py", line 526, in get_file_to_fobj
    with self.get_file(digest) as src:
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/filecacher.py", line 491, in get_file
    self.load(digest)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/filecacher.py", line 448, in load
    text=False)
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/var/local/cache/cms/fs-cache-Worker-1/_temp/tmpVqtFDM'
```

**Comment by stefano-maggiolo** [comment]
How do you try to remove the cache? Seems to survive `rm -f path/to/cache/*`

Despite not particularly advocating doing it while the worker is running, I believe that just removing the "stable" files (i.e., everything but the `_temp` subdirectory) should be fine - I think Linux tells you the files are deleted but keep them around as long as there are file descriptors open for reading them.

**Comment by wil93** [comment]
I tried with `rm -rf /var/local/cache/cms/fs-cache-Worker-*`.

I will try with `rm -rf /var/local/cache/cms/fs-cache-Worker-*/??????*` (that is, without removing the `_temp` subdirectories) and report back.

**Comment by stefano-maggiolo** [comment]
You should be able to just leave out the -r, so that it's not recursive (all the files you want to delete are in the root of the cache anyway).

**Comment by wil93** [comment]
I can't test now, I'll reopen if necessary
