### ISSUE TITLE
AWS returns HTTP status codes 500/404 for user test files

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#681]
Navigating to (contest) -> "User tests" -> "User Test 1" and clicking the "Files" link results in the HTTP code 500 from AWS when requesting `/user_test_file/1`.

AWS log contains:
```
2016-12-10 16:33:18,671 - ERROR [Admin,0 151 web::log_exception] Uncaught exception GET /user_test_file/1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/user_test_file/1', version='HTTP/1.1', remote_ip='127.0.0.1', headers={…})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/base.py", line 166, in newfunc
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/usertest.py", line 65, in get
    user_test = user_test_file.user_test
AttributeError: 'File' object has no attribute 'user_test'
2016-12-10 16:33:18,672 - ERROR [Admin,0 151 base::write_error] Uncaught exception (AttributeError("'File' object has no attribute 'user_test'",)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/base.py", line 166, in newfunc
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/usertest.py", line 65, in get
    user_test = user_test_file.user_test
AttributeError: 'File' object has no attribute 'user_test'

2016-12-10 16:33:18,683 - ERROR [Admin,0 151 web::log_request] 500 GET /user_test_file/1 (127.0.0.1) 15.73ms
```

Steps to reproduce (Ubuntu 16.04):
* Run `cmsDropDB` and `cmsInitDB`
* Add an admin, a contest, a task and a user
* Submit one solution
* Submit a user test
* Try to view the user test files from AWS

Interestingly, submitting another user test and requesting `/user_test_file/2` gives HTTP code 404 instead.

**Comment by andreyv** [comment]
Fixed in #691.
