### ISSUE TITLE
Setting an invalid primary statements value causes status code 500 in CWS

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#683]
Steps to reproduce:
- In AWS, set the task's "Primary statements" setting to "test" (without quotes)
- Try to view this task in CWS

Expected result: AWS does not allow setting invalid values for this setting.

Actual result: CWS fails with status code 500 when viewing the task.

Console output:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/util.py", line 200, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/contest/handlers/task.py", line 72, in get
    self.render("task_description.html", task=task, **self.r_params)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/usr/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "task_description_html.generated.py", line 581, in _tt_execute
    task_primary = json.loads(task.primary_statements)  # task_description.html:42 (via base.html:207)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by stefano-maggiolo** [comment]
Do you care about order of primary statements? i was thinking of replacing the JSON input with checkboxes for each statement

**Comment by stefano-maggiolo** [comment]
(imho: not too important, that's supposed to contain 1-2 languages at most...)

**Comment by andreyv** [comment]
Well, there is already a difference between all statements and primary statements, so I think primary statements could be in any order. We actually don't use this functionality right now, so maybe someone who does can comment better.

**Comment by stefano-maggiolo** [comment]
The 500 error is fixed in aa45df5576a44c53491e42d6cb347edcc0a5e19b

**Comment by stefano-maggiolo** [comment]
Fixed

**Comment by stefano-maggiolo** [comment]
Including preventing admins to add empty-language statements (it was already intended like that, but there was a big in the check).
