### ISSUE TITLE
Regression introduced by recent commits

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#697]
```
2017-01-20 14:34:01,026 - ERROR [<unknown>] Unexpected error when formatting status text: [u'Execution killed with signal %d (could be triggered by violating memory limits)', '11']
Traceback (most recent call last):
  File "/home/wil93/git/cms/cms/grading/__init__.py", line 248, in format_status_text
    return text % tuple(status[1:])
```

This happens because now the `'11'` is a string instead of an integer.

A lot of `"Execution killed with signal %d ..."` should be changed in order to use `%s`.

**Comment by stefano-maggiolo** [comment]
Ah, I was wrong, text is not supposed to be a list of string and it was cmsMake in the wrong!

**Comment by wil93** [comment]
I think the issue (or a similar one?) is still present, somewhere:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/wil93/git/cms/cmstaskenv/Test.py", line 91, in print_at_exit
    s[1])
TypeError: %d format: a number is required, not float
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/wil93/git/cms/cmstaskenv/Test.py", line 91, in print_at_exit
    s[1])
TypeError: %d format: a number is required, not float
```
