### ISSUE TITLE
cms is not giving the score

### ISSUE THREAD

**Issue by ziadxkabakibi** [cms-dev/cms#701]
I submit a solution ,the code compiles then it shows "evaluating" then it still saying evaluating
I use v12
sorry for my bad English

**Comment by wil93** [comment]
Can you find the logs of the Worker process? They should be somewhere in `/usr/local/log/cms/`

**Comment by ziadxkabakibi** [comment]
from log files in "worker" 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 137, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.cpp'
2017/01/27 16:50:16 - INFO [Worker,1/compile submission 1] Starting job.
2017/01/27 16:50:16 - ERROR [Worker,1] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 137, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.cpp'


another one 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 137, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.c'
2017/01/27 17:47:15 - INFO [Worker,1/compile submission 10] Starting job.
2017/01/27 17:47:15 - ERROR [Worker,1] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 137, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.c'
2017/01/27 17:47:15 - INFO [Worker,1/compile submission 10] Starting job.
2017/01/27 17:47:15 - ERROR [Worker,1] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/Worker.py", line 137, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.c'
2017/01/27 17:48:44 - INFO [Worker,1/compile submission 11] Starting job.
2017/01/27 17:48:44 - ERROR [Worker,1] Worker failed.

**Comment by ziadxkabakibi** [comment]
actually I tried solutions with c language and c++ but both of them are not working

**Comment by wil93** [comment]
The error says that the grader.c / grader.cpp files are missing. Are you
trying to use graders? (I.e. do you want users to only write a function
instead of reading and writing to files?). If yes, then you need to upload
those two files using the admin panel. If not, you need to change the
setting for the task in the admin panel so that grader aren't used.

Il sab 28 gen 2017, 08:51 ziadxkabakibi <notifications@github.com> ha
scritto:

**Comment by ziadxkabakibi** [comment]
I edited that now it says "scoring" and stays like that

**Comment by wil93** [comment]
Find the logs for ScoringService (in the same folder)

**Comment by ziadxkabakibi** [comment]
2017/01/28 13:19:51 - ERROR [ScoringService,0] Unexpected error when executing operation `scoring submission 4 on dataset 1'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/io/triggeredservice.py", line 148, in run
    self.execute(to_execute[0])
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/ScoringService.py", line 111, in execute
    score_type = get_score_type(dataset=dataset)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/scoretypes/__init__.py", line 77, in get_score_type
    parameters = json.loads(parameters)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ziadxkabakibi** [comment]
sorry I didn't know about parameters 
thank you very much and I'm so sorry if I wasted your time :-)

**Comment by wil93** [comment]
No problem :+1:
