### ISSUE TITLE
Problems configuring output only task - error 500 in new CMS version

### ISSUE THREAD

**Issue by ashikoff** [cms-dev/cms#718]
May be there is such topic but after using 2 hours to search for one without success I'll post new one.
Situation is this - I'm configuring task which is output only. The contestants are supposed to send file named cmyk.txt to the grader and there is a checker that will grade the submission. I'm configuring the task as OutputOnly and set submission format to ["cmyk.txt"]. I then upload one test with input and output file - cmyk.01.in and cmyk.01.sol.
When I log in contest UI for that task I see file name cmyk.txt next to browse button. All is good until now. Problem is that after I submit a file it is then evaluated and I get message - "Not correct" + "File not submitted". I've tried submitting a file with all possible names - cmyk.txt, cmyk.01.sol and so on.
What is the problem it seems that the submission is ok (I can download the file I've submitted), but when it tries to grade it it cannot find the file I've submitted. I've tried to use standard diff without uploading custom checker and the result is the same

**Comment by akmohtashami** [comment]
As far as I know, the submission format should be set to output_<testcase_codename>.txt
So if you have a single testcase with codename cmyk the submission format should be "output_cmyk.txt"

**Comment by ashikoff** [comment]
Thanks a lot, it worked

**Comment by ashikoff** [comment]
Hello again. I've upgraded to last CMS version 1.3 during the summer and managed to judge first EJOI in Sofia during september on it. However now I'm trying to configure output only task for next tournament and I have a problem:

As mentioned above I'm configuring submission format to be ["output_01.txt"] but when I try to submit solution (or better to say - output txt file)  I get error 500 from the server. Is there any difference in 1.3 from 1.2?

**Comment by lerks** [comment]
Error code 500 is usually an indication of a programming error (a bug) rather than a user error. Could you look at the logs of ContestWebServer (or AdminWebServer) to see if any related information has been recorded? This usually comes in the form of an exception and a traceback. If so, could you post it here?

**Comment by ashikoff** [comment]
Here is the log:

2017-11-19 14:54:17,139 - ERROR [Contest,0] Uncaught exception POST /tasks/test/submit (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/tasks/test/submit', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '1358', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0', 'Host': 'localhost:8888', 'Referer': 'http://localhost:8888/tasks/test/submissions', 'Cookie': 'unread_count="2|1:0|10:1511096049|12:unread_count|4:MA==|8f8deb68237cc49cfacc433903c0e69ca611f40815d42d590b26f142c169d84a"; _xsrf=2|cfd12de1|6b3023965bda54c624f71a4152c42c5c|1511096042; login="2|1:0|10:1511096049|5:login|64:KFZqdWRnZQpwMApWaW1vdGVwCnAxCkYxNTExMDk2MDQ5LjExMTgxMwp0cDIKLg==|518b2fb83125a002d861798e890fb9bcc6580df14bb82bb391be02dc49519930"', 'Upgrade-Insecure-Requests': '1', 'Content-Type': 'multipart/form-data; boundary=---------------------------7037180909102005911262078866'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/server/util.py", line 200, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/server/contest/handlers/tasksubmission.py", line 269, in post
    if error is not None:
UnboundLocalError: local variable 'error' referenced before assignment
2017-11-19 14:54:17,208 - ERROR [Contest,0] Uncaught exception (UnboundLocalError("local variable 'error' referenced before assignment",)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/server/util.py", line 200, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/server/contest/handlers/tasksubmission.py", line 269, in post
    if error is not None:
UnboundLocalError: local variable 'error' referenced before assignment

**Comment by lerks** [comment]
I believe you're hitting on a bug that was fixed in 6e1085390a7b63509b6a9fb5bc49df017f941c6e. What version are you using?
