### ISSUE TITLE
Submissions not moving past Compiling

### ISSUE THREAD

**Issue by rcabreu** [cms-dev/cms#726]
Sample output from LogService:
```
19:00:08,569 - INFO [Evaluation,0] Operations `compile on 15 against dataset 2' and 0 more concluded successfully.
2017-03-18 19:00:08,569 - INFO [Worker,2] Starting job group.
2017-03-18 19:00:08,570 - INFO [Worker,2] [compile submission 15] Starting job.
2017-03-18 19:00:09,740 - INFO [Worker,2] [compile submission 15] Finished job.
2017-03-18 19:00:09,741 - INFO [Worker,2] Finished job group.
2017-03-18 19:00:09,741 - INFO [Worker,2] Executed in 1.172 after free for 5.903; busyness is 54.0%; avg free time is 2.962 avg busy time is 3.477
2017-03-18 19:00:09,742 - INFO [Evaluation,0] `compile on 15 against dataset 2' completed. Success: True.
2017-03-18 19:00:56,607 - INFO [Proxy,0] Operations `sending data of type 0 to ranking' and 3 more concluded successfully.
```

As we can see, submissions are being judged. However, contestants just see them i "Compiling" stage. 
HELP!! Using the newly released cms-1.3.rc0

**Comment by stefano-maggiolo** [comment]
@rcabreu what do you see in AWS? From the logs it looks like it's a compilation failure, do you know if the submitted code compiles?

**Comment by rcabreu** [comment]
@stefano-maggiolo the code we sent compiles. All submissions are experiencing this.
Could we chat (Hangout)? rcabreu@gmail.com

**Comment by stefano-maggiolo** [comment]
Sent invitation

**Comment by ABeltramo** [comment]
Same problem here!
```
log_1  | 2017-03-22 11:11:20,488 - INFO [Contest,0] 302 POST /tasks/baht/submit (172.19.0.1) 134.41ms
log_1  | 2017-03-22 11:11:20,522 - INFO [Evaluation,0] Asking worker 0 to `compile on 1 against dataset 1'.
log_1  | 2017-03-22 11:11:20,553 - INFO [Evaluation,0] Operations `compile on 1 against dataset 1' and 0 more concluded successfully.
log_1  | 2017-03-22 11:11:20,554 - INFO [Worker,0] Starting job group.
log_1  | 2017-03-22 11:11:20,554 - INFO [Worker,0] [compile submission 1] Starting job.
log_1  | 2017-03-22 11:11:20,571 - INFO [Contest,0] 200 GET /tasks/baht/submissions?tOlHo6gvTqxV79v-lu_iZ9rPPT0e2nNsm-41BzTFqxA. (172.19.0.1) 68.08ms
log_1  | 2017-03-22 11:11:20,567 - ERROR [Worker,0] Worker failed.
log_1  | Traceback (most recent call last):
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/service/Worker.py", line 124, in execute_job_group
log_1  |     task_type.execute_job(job, self.file_cacher)
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/grading/TaskType.py", line 249, in execute_job
log_1  |     self.compile(job, file_cacher)
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/grading/tasktypes/Batch.py", line 158, in compile
log_1  |     sandbox = create_sandbox(file_cacher, job.multithreaded_sandbox)
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/grading/TaskType.py", line 63, in create_sandbox
log_1  |     sandbox = Sandbox(multithreaded, file_cacher)
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/grading/Sandbox.py", line 852, in __init__
log_1  |     "(error %d)" % (pretty_print_cmdline(box_cmd), ret))
log_1  | SandboxInterfaceException: Failed to initialize sandbox with command: 'isolate' '--cg' '--box-id=10' '--init' (error 2)
log_1  | 2017-03-22 11:11:20,586 - INFO [Worker,0] Executed in 0.033 after free for 0.000; busyness is 100.0%; avg free time is 0.000 avg busy time is 0.000 
log_1  | 2017-03-22 11:11:20,600 - ERROR [Evaluation,0] Worker,0 signaled RPC for method execute_job_group was unsuccessful: JobException: u'Worker failed.'
log_1  | Traceback (most recent call last):
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request
log_1  |     response["__data"] = method(**request["__data"])
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/service/Worker.py", line 153, in execute_job_group
log_1  |     raise JobException(err_msg)
log_1  | JobException: u'Worker failed.'
log_1  | .
log_1  | 2017-03-22 11:11:20,602 - ERROR [Evaluation,0] Received error from Worker: `JobException: u'Worker failed.'
log_1  | Traceback (most recent call last):
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request
log_1  |     response["__data"] = method(**request["__data"])
log_1  |   File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cms/service/Worker.py", line 153, in execute_job_group
log_1  |     raise JobException(err_msg)
log_1  | JobException: u'Worker failed.'
log_1  | '.
```
Git clone the latest v1.3.
Executing `isolate --box-id=10 -cg --init` work on console.

**Comment by jihoon-ko** [comment]
I think I am encountering same bug, could you help me??

**Comment by lerks** [comment]
Not sure if this ended up being fixed privately, but I had a similar issue while testing #737. It was caused by an exception being raised when storing a Job's content back into a Submission/UserTest, which wasn't caught and therefore not stored on the logs or sent to LogService. My conjecture is that in this case you may have been bitten by something akin to #736 or #666, which similarly caused an exception to be raised but not reported. It's worth trying with that commit applied to see if the issue persists.

**Comment by lerks** [comment]
I wanna be optimistic here and say that by removing SMC (see #737) this has been fixed. If not please reopen.
