### ISSUE TITLE
"Large object not found" or something, when an import was canceled and restarted

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#766]
I imported a contest with `cmsImportContest -i .` and then canceled with CTRL+C during the import of the tasks.

Then I reimported everything, but one of the tasks was already corrupted (I guess for the CTRL+C).

In particular, I think the corruption causes some hashes to be associated with nonexisting files. When importing again, CMS sees the same hash, and uses the same reference to the same nonexisting file.

In my case, some testcases were corrupted.

To solve this, I just changed the seed values in the `gen/GEN` file and recreated new inputs (with different hashes) and imported a new dataset.

**Comment by lerks** [comment]
Please attache the error message and/or the traceback you're seeing.

**Comment by wil93** [comment]
```
2017-05-19 07:09:26,415 - ERROR [Worker,6 171 Worker::execute_job_group] Worker failed.
Traceback (most recent call last):
  File "/cms/cms/service/Worker.py", line 122, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/cms/cms/grading/TaskType.py", line 245, in execute_job
    self.evaluate(job, file_cacher)
  File "/cms/cms/grading/tasktypes/Batch.py", line 251, in evaluate
    sandbox.create_file_from_storage(filename, digest)
  File "/cms/cms/grading/Sandbox.py", line 309, in create_file_from_storage
    self.file_cacher.get_file_to_fobj(digest, file_)
  File "/cms/cms/db/filecacher.py", line 526, in get_file_to_fobj
    with self.get_file(digest) as src:
  File "/cms/cms/db/filecacher.py", line 491, in get_file
    self.load(digest)
  File "/cms/cms/db/filecacher.py", line 451, in load
    fobj = self.backend.get_file(digest)
  File "/cms/cms/db/filecacher.py", line 232, in get_file
    return fso.get_lobject(mode='rb')
  File "/cms/cms/db/fsobject.py", line 398, in get_lobject
    lobj = LargeObject(self.loid, mode)
  File "/cms/cms/db/fsobject.py", line 121, in __init__
    "%s." % (self.loid), cursor)
  File "/cms/cms/db/fsobject.py", line 170, in _execute
    raise IOError(message)
IOError: Couldn't open large object with LOID 217493.
```

**Comment by lerks** [comment]
Thanks.

If your interpretation is correct (it most likely is) I suspect you've managed to kill your program between lines 589 and 598 of https://github.com/cms-dev/cms/blob/7ba7076e39616b2880a9fe3876ffd7c2b7469e8e/cms/db/filecacher.py. Very good aim! ;)

You don't happen to have kept the traceback that was printed when you hit ctrl+c, do you?

The best solution to this issue would be to have all components involved here (the importer, DBBackend.put_file and LargeObject) use the same database session and transaction (now they each have their own). I don't know if this is even possible.

**Comment by stefano-maggiolo** [comment]
How about disabling Ctrl-C during that range of lines? I suspect you don't actually need good aim, as the program spends most of the time there, I'd guess. My take:

```py
import signal                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
class DelayedExit(object):                                                                                                                                                                                                                     
  def __init__(self):                                                                                                                                                                                                                          
    self.terminate = False                                                                                                                                                                                                                     
                                                                                                                                                                                                                                               
  def handle(self):                                                                                                                                                                                                                            
    self.terminate = True                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
  def __enter__(self):                                                                                                                                                                                                                         
    self.original = signal.signal(signal.SIGINT, lambda x, y: self.handle())                                                                                                                                                                   
    return self                                                                                                                                                                                                                                
                                                                                                                                                                                                                                               
  def __exit__(self, exc_type, exc_value, exc_tb):                                                                                                                                                                                             
    self.original = signal.signal(signal.SIGINT, self.original)                                                                                                                                                                                
    if exc_type is not None:                                                                                                                                                                                                                   
      return False                                                                                                                                                                                                                             
    if self.terminate:                                                                                                                                                                                                                         
      raise KeyboardInterrupt()                                                                                                                                                                                                                
    return True                                                                                                                                                                                                                                
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
print "A"                                                                                                                                                                                                                                      
with DelayedExit():                                                                                                                                                                                                                            
  a = raw_input()                                                                                                                                                                                                                              
  print "A1"                                                                                                                                                                                                                                   
print "B"                                                                                                                                                                                                                                      
a = raw_input()                                                                                                                                                                                                                                
print "C"                                                                                                                                                                                                                                      
```

Ctrl-C is ignored during the first raw_input, but it makes the program terminate after printing A1. Another exception instead (e.g., Ctrl-D) doesn't print A1.

**Comment by stefano-maggiolo** [comment]
This should be fixed (properly, unlike my shortsighted proposal) by @wafrelka and @bblackham.
