### ISSUE TITLE
HTTP 500 on invalid GET /<contest>/login request

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#810]
When CWS is running in multicontest mode, sending an (invalid) `GET /<contest>/login` request results in internal server error:

```
2017-12-03 18:57:27,577 - ERROR [Contest,0 5 web::log_exception] Uncaught exception GET /test/login (10.0.2.2)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/test/login', version='HTTP/1.1', remote_ip='10.0.2.2', headers={…})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2017-12-03 18:57:27,594 - ERROR [Contest,0 5 base::write_error] Uncaught exception (TypeError('get() takes exactly 1 argument (2 given)',)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)

2017-12-03 18:57:27,604 - ERROR [Contest,0 5 web::log_request] 500 GET /test/login (10.0.2.2) 32.81ms
```

Probably this should return HTTP status code 405 Method Not Allowed or something else instead of 500 Internal Server Error.

I think this goes like this: `LoginHandler` -> `ContestHandler` -> `BaseHandler` -> `get()`, which doesn't have `@multicontest` decorator but is passed the contest name.

CC @wil93

**Comment by lerks** [comment]
This was fixed in #854.
