### ISSUE TITLE
HTTP 500 on invalid contest in multicontest mode

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#812]
In multicontest mode, navigating to `http://<cws>/foo` when the contest `foo` does not exist causes an internal server error:

```
2017-12-09 18:57:35,453 - ERROR [Contest,0 10 web::log_exception] Uncaught exception GET /foo (10.0.2.2)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/foo', version='HTTP/1.1', remote_ip='10.0.2.2', headers={…})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 100, in prepare
    self.choose_contest()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 132, in choose_contest
    self.r_params = self.render_params()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 394, in render_params
    lang_codes = self.langs.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2017-12-09 18:57:35,454 - ERROR [Contest,0 10 base::write_error] Uncaught exception (AttributeError("'NoneType' object has no attribute 'keys'",)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 100, in prepare
    self.choose_contest()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 132, in choose_contest
    self.r_params = self.render_params()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 394, in render_params
    lang_codes = self.langs.keys()
AttributeError: 'NoneType' object has no attribute 'keys'

2017-12-09 18:57:35,458 - ERROR [Contest,0 10 web::log_request] 500 GET /foo (10.0.2.2) 10.51ms
```
Probably the response should be HTTP 404 or similar instead.

**Comment by edomora97** [comment]
I've implemented a fix for this, if you like it we can merge in here: https://github.com/algorithm-ninja/cms/commit/fb87169058cbd87736dbf132c3ed0d53861a251f

**Comment by stefano-maggiolo** [comment]
Thank you @edomora97 , I'll merge it with minor changes - note that there is no need to set the status code in write_error or to call it, that method is called by Tornado when an error is raised elsewhere.

**Comment by stefano-maggiolo** [comment]
4386a29f2891825adc5a1d72477b309ddc397a45
