### ISSUE TITLE
AWS: Download ranking as text fails with Python 3

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#902]
With CMS master and Python 3, navigate to Contest -> Ranking -> Download as text in AWS. Output:
```
2018-03-17 20:30:41,830 - ERROR [Admin,0 12 base::write_error] Uncaught exception (ImportError("cannot import name 'izip'",)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 2898, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/server/admin/handlers/base.py", line 184, in newfunc
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/server/admin/handlers/contestranking.py", line 91, in get
    self.render("ranking.txt", **self.r_params)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 865, in render_string
    return t.generate(**namespace)
  File "/usr/lib/python3/dist-packages/tornado/template.py", line 348, in generate
    return execute()
  File "ranking_txt.generated.py", line 4, in _tt_execute
    from itertools import izip  # ranking.txt:1 (via ranking.txt:1)
ImportError: cannot import name 'izip'
```

**Comment by lerks** [comment]
It turns out this will be fixed in #900. I'll keep this open until that is merged.
