### ISSUE TITLE
ScoringService fails with "'StandardError' is not defined" while reporting an error

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#928]
When scoring a submission fails, ScoringService is supposed to log an error describing the failure. Instead, it encounters another error while processing the original error.

Typical output (after corrupting Score Parameters and re-running scoring on a submission):
```
2018-04-07 22:39:20,156 - ERROR [Scoring,0 7 triggeredservice::run] Unexpected error when executing operation `scoring submission 6 on dataset 1'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/io/triggeredservice.py", line 152, in run
    self.execute(to_execute[0])
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/service/ScoringService.py", line 104, in execute
    score_type = dataset.score_type_object
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/db/task.py", line 472, in score_type_object
    self.score_type, self.score_type_parameters, public_testcases)
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/grading/scoretypes/__init__.py", line 62, in get_score_type
    return class_(parameters, public_testcases)
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/grading/ScoreType.py", line 80, in __init__
    self.max_scores()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/grading/ScoreType.py", line 346, in max_scores
    targets = self.retrieve_target_testcases()
  File "/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/grading/ScoreType.py", line 330, in retrieve_target_testcases
    raise StandardError(
NameError: name 'StandardError' is not defined
```

Note: this is on Python 3. Text search reveals multiple occurrences of `StandardError` usage in `ScoreType.py`.

**Comment by lerks** [comment]
From http://python3porting.com/differences.html:
> Python 2 has an exception class called StandardError that has been removed in Python 3. Use Exception instead.

Should be easy to fix.

**Comment by andreyv** [comment]
I found this too now and I realized I could've just prepared a trivial pull request for this :)

**Comment by lerks** [comment]
Oh please go ahead! I currently have other things on my plate and wouldn't have gotten to this anytime soon. ;)
