### ISSUE TITLE
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 60

### ISSUE THREAD

**Issue by valiro21** [cms-dev/cms#969]
**Description:** Contest selection page is not loading at all for some requests.

**Steps to reproduce:**
1. Start cms services separately using haproxy.
2. Open multiple requests to the contest selection page, for example with ab: ```ab -k -c 350 -n 2000 http://localhost:8888/```

**Expected:** Users should be able to connect.

**Actual:** Requests are left hanging, the page does not load in any way.

### Logs

2018-05-24 07:31:41,353 - ERROR [Contest,0] Uncaught exception (TimeoutError('QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 60',)) while processing a request: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 78, in prepare
    self.choose_contest()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.4.dev0-py2.7.egg/cms/server/contest/handlers/contest.py", line 113, in choose_contest
    .filter(Contest.name == contest_name).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
    **kw
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1019, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1024, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1133, in _do_get
    (self.size(), self.overflow(), self._timeout))
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 60

### System Information

**CMS version:** master
**Was CMS installed:** yes, inside docker
**Using a virtualenv:** no
**Postgres version:** 9.4.8
**Distribution and version:** Linux 2d903941ba4e 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lerks** [comment]
If I understand this correctly, it is not surprising. CWS is able to handle some level of concurrent HTTP request load but definitely not the type of spikes you flooded it with. Each CWS can have at most 15 simultaneous connections to the database open at any time. If all are in use, new requests need to wait for a previous request to finish. If there are too many requests, some will timeout.

This scenario is explained in the troubleshooting section of the documentation, together with possible mitigations:
https://cms.readthedocs.io/en/v1.3/Troubleshooting.html#servers
